[package]
name = "reth-fuzz-harness"
version.workspace = true
description = "Typed fuzz harness ABI for reth."
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[lints]
workspace = true

[dependencies]
alloy-consensus = { workspace = true, features = ["secp256k1"] }
alloy-eips.workspace = true
bincode.workspace = true
serde = { workspace = true, features = ["derive"] }
